language: rust
dist: trusty
sudo: required

services:
  - docker

matrix:
  include:
    - env: TARGET=arm-linux-androideabi
    - env: TARGET=aarch64-linux-android
    - env: TARGET=i686-linux-android
    - env: TARGET=x86_64-linux-android

    - os: osx
      env: TARGET=x86_64-apple-darwin NO_ADD=1
    - os: osx
      env: TARGET=i686-apple-darwin

    - env: TARGET=x86_64-unknown-linux-gnu NO_ADD=1
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=asmjs-unknown-emscripten

    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu NO_ADD=1
    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu NO_ADD=1

install:
  - if [ -z "$NO_ADD" ]; then rustup target add $TARGET; fi

script:
  - cargo generate-lockfile
  - ./ci/run-docker.sh $TARGET

notifications:
  email:
    on_success: never

branches:
  only:
  - master
